$kind: http-request
name: Get All Environments
method: GET
url: "{{baseUrl}}{{apiPrefix}}/projects/{{projectId}}/environments"
order: 2000
headers:
  Authorization: Bearer {{authToken}}
  organization-id: "{{organizationId}}"
